project_id = "cmaghzavkdbpbmfnfiln"

[functions.submit-request]
verify_jwt = false

[functions.upload-to-drive]
verify_jwt = false

[functions.send-beta-notification]
verify_jwt = false

[functions.send-intake-link]
verify_jwt = false

[functions.send-denial-email]
verify_jwt = false

[functions.send-credentials-notification]
verify_jwt = false

[functions.send-workflow-notification]
verify_jwt = false
